%RUN_BEARING_COMPARISON Bearing-control comparison from the simulation section.

clear; clc;
projectRoot = fileparts(fileparts(mfilename('fullpath')));
addpath(fullfile(projectRoot, 'src'));

dt = 0.01;
steps = 5000;
gain = 1.0;
misalignedAgent = 1;
theta = deg2rad(5.0);

spec = paperFiveAgentSpec();
figuresDir = fullfile(projectRoot, 'results', 'figures');
logsDir = fullfile(projectRoot, 'results', 'logs');
ensureDir(figuresDir);
ensureDir(logsDir);
times = (0:steps)' * dt;

controllerAligned = @(positions) bearingControlInput( ...
    positions, spec.bearingEdges, spec.desiredBearings, gain, 0, 0);
trajectoryAligned = simulateFormation(spec.initialPositions, controllerAligned, dt, steps);
errorsAligned = bearingErrors(trajectoryAligned, spec.bearingEdges, spec.desiredBearings);

controllerMisaligned = @(positions) bearingControlInput( ...
    positions, spec.bearingEdges, spec.desiredBearings, gain, misalignedAgent, theta);
trajectoryMisaligned = simulateFormation(spec.initialPositions, controllerMisaligned, dt, steps);
errorsMisaligned = bearingErrors(trajectoryMisaligned, spec.bearingEdges, spec.desiredBearings);

plotFormationTrajectory( ...
    trajectoryAligned, ...
    fullfile(figuresDir, 'bearing_control_no_misalignment_trajectory.png'), ...
    'Bearing-Based Control Without Misalignment');
plotErrorSeries( ...
    times, errorsAligned, ...
    fullfile(figuresDir, 'bearing_control_no_misalignment_errors.png'), ...
    'Bearing Errors Without Misalignment', ...
    'bearing error norm');

plotFormationTrajectory( ...
    trajectoryMisaligned, ...
    fullfile(figuresDir, 'bearing_control_with_misalignment_trajectory.png'), ...
    'Bearing-Based Control With Misalignment');
plotErrorSeries( ...
    times, errorsMisaligned, ...
    fullfile(figuresDir, 'bearing_control_with_misalignment_errors.png'), ...
    'Bearing Errors With Misalignment', ...
    'bearing error norm');

metrics = struct();
metrics.no_misalignment = struct( ...
    'final_bearing_rmse', sqrt(mean(errorsAligned(end, :) .^ 2)), ...
    'final_max_bearing_error', max(errorsAligned(end, :)));
metrics.with_misalignment = struct( ...
    'final_bearing_rmse', sqrt(mean(errorsMisaligned(end, :) .^ 2)), ...
    'final_max_bearing_error', max(errorsMisaligned(end, :)));

writeJson(fullfile(logsDir, 'bearing_comparison_metrics.json'), metrics);
disp(jsonencode(metrics));
